### ISSUE TITLE
Detect non-vscode terminal usage

### ISSUE THREAD

**Issue by vanderwb** [neumanbrett/qvscode#3]
It looks like you could interrogate this environment variable: `TERM_PROGRAM=vscode` and if it isn't set properly, infer that it isn't running in a VSCode terminal and exit gracefully with a help message.

**Comment by neumanbrett** [comment]
Debatable if graceful but now instructs the user to launch in VSCode in 1f3fd22b4c0be33e98f550b2a7897d4480490633
